# Generated by Django 5.2.7 on 2025-10-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
